---
name: "Docker image build"

on:
  workflow_dispatch:

jobs:
  docker-image:
    name: "Docker image"
    runs-on: ubuntu-latest
    
    steps:
      - name: "Checkout Source Code"
        uses: actions/checkout@v4

      - name: "Docker image build"
        run: docker image build -t aariasoman/java-app:v1 .
